routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});


$router->get('/checkout-complete/{ordernr}', function () use ($router) {
    return view('checkout.checkout-complete');
    exit;
});

//Route::get('/status/update', 'PageController@updateStatus')->name('switch.update.same_address');

//Route::middleware(['checkIp'])->group(function () {
//
//    Route::get('/', function () {
//        return view('pages.underconstruction');
//    });

    Route::get('/', "PageController@home");
    Route::get('/feeds', "FeedController@feedGenerator");



    Route::get('/monitor', "PageController@monitor");
    Route::post('/succes', "DosController@post_orderbevestiging");


    Route::get("dashboard", "AnalyticsController@pageviews");
    Route::get('/statistics', function () {
        $import = new \App\Http\Controllers\AnalyticsController();
        $import->MailStatistics();
        exit;
    });

//
//Route::get('/pdf',function(){
//    return view('pages.pdf');
//
//});

    Route::post('succes', 'DosController@goedkeuring');
    Route::post('fail', 'DosController@afkeuring');

    Route::get('/about_us', "PageController@aboutus");
    Route::get('/gallery', "PageController@gallery");
    Route::get('/b2b', "PageController@b2b");
    Route::get('/dos', "DosController@orders")->name('dos');
    Route::any("/getvip/{id}", "DosController@getVip");
    Route::any("/productswitch", "DosController@productSwitch")->name('switch.update.status');

    Route::get('/feed', "FeedController@makeFeed");


    Route::any('/dos/{order}', function ($order) {
        $import = new \App\Http\Controllers\DosController();
        $import->PDFgenerator($order);
        exit;
    });

    Route::get('/storeanalytics', function () {
        $import = new \App\Http\Controllers\AnalyticsController();
        $import->storeAnalytics();
        exit;
    });
    Route::get('/refreshMonitor', function () {
        $import = new \App\Http\Controllers\ImportController();
        $import->refreshMonitor();
        exit;
    });


    Route::resource('subcategory-grid', 'index@CustomSearchController');


    Route::get('/mollie', [
            'uses' => 'OrderController@doOrder'
        ]
    );

    Route::post('/orderhook', 'OrderController@doHook');

    Route::get('/healthcheck', function () {
        $import = new \App\Http\Controllers\ImportController();
        $import->healthcheck();

    });

    Route::get('/feed', function () {
        $import = new \App\Http\Controllers\FeedController();
        $import->feedGenerator();
        exit;
    });



    Route::any('/order-tracking/{page}', [
        'uses' => 'UserController@getSingleOrders',
        'as' => 'singleorder.track'
    ]);

    Route::get('/checkout', [
        'uses' => 'ProductController@getCheckout',
        'as' => 'shop.checkout'
    ]);

    Route::any('/category/subcategory-grid/single-product/{page}', [
        'uses' => 'ProductController@viewProduct',
        'as' => 'pages.single-product-grid'
    ]);

    Route::any('/category/subcategory-list/single-product/{page}', [
        'uses' => 'ProductController@viewProduct',
        'as' => 'pages.single-product-list'
    ]);
//    Route::any('/category/{id}', [
//        'uses' => 'ProductController@getCategory',
//        'as' => 'category.category'
//    ]);

    Route::any('/category/{page}', [
        'uses' => 'ProductController@getCategory',
        'as' => 'category.category'
    ]);

    Route::any('/contacts', [
        'uses' => 'ProductController@getContact',
        'as' => 'category.category'
    ]);


    Route::any('/categoryall', [
        'uses' => 'ProductController@getCategoryMenu',
        'as' => 'category.category'
    ]);

    Route::any('/category/subcategory-grid/{page}', [
        'uses' => 'ProductController@getSubCategoryGrid',
        'as' => 'category.category'
    ]);

    Route::any('/category/search/{page}', [
        'uses' => 'ProductController@getSearch',
        'as' => 'category.category'
    ]);


    Route::any('/category/subcategory-list/{page}', [
        'uses' => 'ProductController@getSubCategoryList',
        'as' => 'category.category'
    ]);

    Route::get('/product/filter-list', [
        'uses' => 'ProductController@getFilterProduct',
        'as' => 'pages.filter-product-list'
    ]);
    Route::get('/product/filter-grid', [
        'uses' => 'ProductController@getFilterProduct',
        'as' => 'pages.filter-product-grid'
    ]);


    Route::get('/shop-grid-ls', [
        'uses' => 'ProductController@getIndex',
        'as' => 'product.page'
    ]);
    Route::get('/shop-list-ls', [
        'uses' => 'ProductController@getIndex2',
        'as' => 'product.page'
    ]);



    Route::get('/shoppingcart', [
        'uses' => 'ProductController@getCart',
        'as' => 'shoppingcart'
    ]);

//Route::get('/', [
//    'uses' => 'ProductController@getCartHeader',
//    'as' => 'shoppingcart.header'
//]);

    Route::get('/addToCart/{id}', [
        'uses' => 'ProductController@getAddToCart',
        'as' => 'product.addToCart'

    ]);
    Route::post('/addToCart', [
        'uses' => 'ProductController@getAddToCart',
        'as' => 'product.addingToCart'

    ]);

    Route::get('/reduce/{id}', [
        'uses' => 'ProductController@getReduceByOne',
        'as' => 'product.reduceByOne'
    ]);
    Route::get('/increase/{id}', [
        'uses' => 'ProductController@getIncreaseByOne',
        'as' => 'product.increaseByOne'
    ]);
    Route::post('/change-product-quantity', [
        'uses' => 'ProductController@changeProductQty',
        'as' => 'product.changeProductQuantity'
    ]);

    Route::get('/remove/{id}', [
        'uses' => 'ProductController@getRemoveItem',
        'as' => 'product.remove'
    ]);


    Route::get('/checkout-afronding', [
        'uses' => 'OrderController@getAfronding',
        'as' => 'checkout-afronding',

    ]);

    Route::any('/checkout-address', [
        'uses' => 'OrderController@getCheckoutAddress',
        'as' => 'checkout-address',

    ]);

    Route::post('/checkout-address-update', [
        'uses' => 'OrderController@updateCheckoutAddress',
        'as' => 'checkout-address-update',

    ]);

    Route::post('formulierbandenGebruikt-verzenden', [
        'uses' => 'PageController@post_formulierbandenGebruikt_verzenden'
    ]);


    Route::group(['prefix' => ''], function () {

        Route::get('/account-register', [
            'uses' => 'UserController@getSignup',
            'as' => 'account-register',
            'middleware' => 'guest'

        ]);


        Route::post('/account-register', [
            'uses' => 'UserController@postSignup',
            'as' => 'account-register',
            'middleware' => 'guest'

        ]);

        Route::get('/account-login', [
            'uses' => 'UserController@getSignin',
            'as' => 'account-login',
            'middleware' => 'guest'

        ]);
//
//    Route::get('/account-login', [
//        'uses' => 'UserController@getSignin',
//        'as' => 'account-login',
//        'middleware' => 'auth'
//
//    ]);

        Route::post('/account-login', [
            'uses' => 'UserController@postSignin',
            'as' => 'account-login',
            'middleware' => 'guest'

        ]);

        Route::get('/account-profile', [
            'uses' => 'UserController@getProfile',
            'as' => 'account.profile',
            'middleware' => 'auth'
        ]);


        Route::post('/account-profile-update', [
            'uses' => 'UserController@UpdateProfile',
            'as' => 'Update.Profile',
            'middleware' => 'auth'

        ]);

        Route::get('/account-password-recovery', [
            'uses' => 'UserController@GetPasswordReset',
            'as' => 'Update.Profile',
            'middleware' => 'guest'

        ]);

        Route::get('/account-orders', [
            'uses' => 'UserController@getOrders',
            'as' => 'account.orders',
            'middleware' => 'auth'

        ]);
        Route::get('/account-single-ticket', [
            'uses' => 'UserController@getSingleTicket',
            'as' => 'account.single-ticket',
            'middleware' => 'auth'

        ]);
        Route::get('/account-ticket-details', [
            'uses' => 'UserController@getTicketDetails',
            'as' => 'account.ticket-details',
            'middleware' => 'auth'

        ]);
        Route::get('/account-tickets', [
            'uses' => 'UserController@getTicket',
            'as' => 'account.account-tickets',
            'middleware' => 'auth'

        ]);
        Route::any('/account-address', [
            'uses' => 'UserController@getAddress',
            'as' => 'account.account-address',
            'middleware' => 'auth'

        ]);
        Route::any('/account-address-update', [
            'uses' => 'UserController@updateAddress',
            'as' => 'account.account-address',
            'middleware' => 'auth'

        ]);
        Route::get('/account-wishlist', [
            'uses' => 'UserController@getWishlist',
            'as' => 'account.account-wishlist',
            'middleware' => 'auth'

        ]);


        Route::get('/logout', [
            'uses' => 'UserController@getLogout',
            'as' => 'logout',
            'middleware' => 'auth'

        ]);
    });

    Route::get('/cart/destroy', [
        'uses' => 'ProductController@destroyCart',
        'as' => 'product.destroyCart'
    ]);


    Route::get('{page}', 'GetIndexController@getIndex');

resources/views/layouts/about.blade.php
<head>

    <link href="/bootstrap/css/bootstrap.css" rel="stylesheet">
    <link id="mainStyles" rel="stylesheet" media="screen" href="/css/styles.min.css">
    <link rel="stylesheet" media="screen" href="/css/vendor.min.css">


    <!-- Loading Template CSS -->
    <link href="/css2/style.css" rel="stylesheet">
    <link href="/css2/animate.css" rel="stylesheet">
    <link href="/css2/style-magnific-popup.css" rel="stylesheet">

    <!-- Fonts -->
    <link href="/css2/font-awesome.min.css" rel="stylesheet">
    <link href="/css2/icons-main.css" rel="stylesheet">
    <link href="/css2/icons-helper.css" rel="stylesheet">

    <!-- RS5.0 Main Stylesheet -->
    <link rel="stylesheet" type="text/css" href="/revolution/css/settings.css">

    <!-- RS5.0 Layers and Navigation Styles -->
    <link rel="stylesheet" type="text/css" href="/revolution/css/layers.css">
    <link rel="stylesheet" type="text/css" href="/revolution/css/navigation.css">

    <!-- Google Fonts -->
    <link href='https://fonts.googleapis.com/css?family=Tangerine:400,700' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Lora:400,400italic,700' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>

    <!-- Font Favicon -->
    <link rel="shortcut icon" href="images/favicon.ico">

    <script src="/js/html5shiv.js"></script>
    <script src="/js/respond.min.js"></script>
    <script src="/js/scripts.min.js"></script>
</head>

<body>


{{--@include('templates.banner')--}}
@include('templates.video')

@include('templates.quote')

@include('templates.story')
{{--@include('templates.productdetails')--}}





<script src="/js/jquery-1.11.3.min.js"></script>
<script src="/js/bootstrap.min.js"></script>
<script src="/js/bootstrap-select.js"></script>
<script src="/js/bootstrap-switch.js"></script>
<script src="/js/jquery.magnific-popup.min.js"></script>
<script src="/js/jquery.nav.js"></script>
<script src="/js/jquery.scrollTo-min.js"></script>
<script src="/js/SmoothScroll.js"></script>
<script src="/js/wow.js"></script>
<script src="/js/instafeed.js"></script>
<script src="/js/instagram.js"></script>

<script type="text/javascript" src="/revolution/js/jquery.themepunch.tools.min.js"></script>
<script type="text/javascript" src="/revolution/js/jquery.themepunch.revolution.min.js"></script>

<script type="text/javascript" src="/revolution/js/extensions/revolution.extension.slideanims.min.js"></script>
<script type="text/javascript" src="/revolution/js/extensions/revolution.extension.layeranimation.min.js"></script>
<script type="text/javascript" src="/revolution/js/extensions/revolution.extension.navigation.min.js"></script>
<script type="text/javascript" src="/revolution/js/extensions/revolution.extension.actions.min.js"></script>
<script type="text/javascript" src="/revolution/js/extensions/revolution.extension.carousel.min.js"></script>

<!-- begin custom script-->
<script src="/js/custom.js"></script>
<script src="/js/plugins.js"></script>

<script type="text/javascript" src="/revolution/js/extensions/revolution.extension.video.min.js"></script>
<script type="text/javascript" src="/revolution/js/extensions/revolution.extension.kenburn.min.js"></script>

</body>

resources/views/layouts/bedrijven.blade.php
<head>

    <link href="/bootstrap/css/bootstrap.css" rel="stylesheet">
    <link id="mainStyles" rel="stylesheet" media="screen" href="/css/styles.min.css">
    <link rel="stylesheet" media="screen" href="/css/vendor.min.css">


    <!-- Loading Template CSS -->
    <link href="/css2/style.css" rel="stylesheet">
    <link href="/css2/animate.css" rel="stylesheet">
    <link href="/css2/style-magnific-popup.css" rel="stylesheet">

    <!-- Fonts -->
    <link href="/css2/font-awesome.min.css" rel="stylesheet">
    <link href="/css2/icons-main.css" rel="stylesheet">
    <link href="/css2/icons-helper.css" rel="stylesheet">

    <!-- RS5.0 Main Stylesheet -->
    <link rel="stylesheet" type="text/css" href="/revolution/css/settings.css">

    <!-- RS5.0 Layers and Navigation Styles -->
    <link rel="stylesheet" type="text/css" href="/revolution/css/layers.css">
    <link rel="stylesheet" type="text/css" href="/revolution/css/navigation.css">

    <!-- Google Fonts -->
    <link href='https://fonts.googleapis.com/css?family=Tangerine:400,700' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Lora:400,400italic,700' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>

    <!-- Font Favicon -->
    <link rel="shortcut icon" href="images/favicon.ico">

    <script src="/js/html5shiv.js"></script>
    <script src="/js/respond.min.js"></script>
    <script src="/js/scripts.min.js"></script>
</head>

<body>


<section id="about" class="section-grey" style="background-color: #6e5e4e; border-bottom: 1px solid #e1e7ec;">

    <!--begin container-->
    <div class="container">

        <!--begin row-->
        <div class="row">

            <!--begin col-md-6-->
            <div class="col-md-6 text-center padding-top-50 padding-bottom-50 wow slideInLeft">

                <span class="comic-text" style="color: whitesmoke">Lorando & Morini</span>

                <h2 class="section-title" style="color: antiquewhite; padding-top: 60px">Voor jouw bedrijf</h2>

                <p style="font-size: 16px; color: whitesmoke">
                    Koffiebranderij en leverancier van de meest verse en unieke single state origin Arabica koffie van Nederland. Lorando en Morini levert dagelijks vers gebrande koffie en koffiebonen aan bedrijven, horeca, restaurants en hotels.

                    <br><br>
                    Vanuit onze ambachtelijke koffiebranderij in Rotterdam delen wij onze passie en ontdekkingen van de lekkerste koffiesoorten met echte liefhebbers.
                    <br><br>

                    Kortingen voor grote afnames:
                    <br><br>

                    5 Kilo (per week) – 7,5% korting<br>
                    10 Kilo (per week) – 10% korting<br><br>
                    Wij leveren ook in zakken van 5 kilo.

                </p>
                <img src="/img/whitelabel-1.jpg" alt="picture" class="width-100" style="padding-top: 170px">





            </div>
            <!--end col-md-6-->

            <!--begin col-md-6-->
            <div class="col-md-6 wow slideInRight text-center padding-top-50 padding-bottom-50 wow" >

                <img src="/img/lorandomorini-5.jpg" style="height: 50%;"  alt="picture" class="width-100">


                <br>
                <br>
                <br>   <br>
                <br>
                <br>

                <span class="comic-text" style="color:whitesmoke" >Private Label</span>

                <h2 class="section-title" style="color: antiquewhite; padding-top: 60px">Voor jouw gebrand met jouw logo</h2>


                <p style="font-size: 16px; color: whitesmoke">

                    Altijd al een eigen koffie-merk willen starten? <br><br>
                    Dat kan in samenwerking met Lorando & Morini. In opdracht van jou kunnen we samen met jou koffie branden.
                    Vervolgens kan de koffie geleverd worden in zakken met jouw logo er op. <br><br>
                    Benieuwd naar prijzen en de mogelijkheden? Neem dan contact op!

                </p>


            </div>
            <!--end col-md-6-->

        </div>
        <!--end row-->

    </div>
    <!--end container-->

</section>





<script src="/js/jquery-1.11.3.min.js"></script>
<script src="/js/bootstrap.min.js"></script>
<script src="/js/bootstrap-select.js"></script>
<script src="/js/bootstrap-switch.js"></script>
<script src="/js/jquery.magnific-popup.min.js"></script>
<script src="/js/jquery.nav.js"></script>
<script src="/js/jquery.scrollTo-min.js"></script>
<script src="/js/SmoothScroll.js"></script>
<script src="/js/wow.js"></script>
<script src="/js/instafeed.js"></script>
<script src="/js/instagram.js"></script>

<script type="text/javascript" src="/revolution/js/jquery.themepunch.tools.min.js"></script>
<script type="text/javascript" src="/revolution/js/jquery.themepunch.revolution.min.js"></script>

<script type="text/javascript" src="/revolution/js/extensions/revolution.extension.slideanims.min.js"></script>
<script type="text/javascript" src="/revolution/js/extensions/revolution.extension.layeranimation.min.js"></script>
<script type="text/javascript" src="/revolution/js/extensions/revolution.extension.navigation.min.js"></script>
<script type="text/javascript" src="/revolution/js/extensions/revolution.extension.actions.min.js"></script>
<script type="text/javascript" src="/revolution/js/extensions/revolution.extension.carousel.min.js"></script>

<!-- begin custom script-->
<script src="/js/custom.js"></script>
<script src="/js/plugins.js"></script>

<script type="text/javascript" src="/revolution/js/extensions/revolution.extension.video.min.js"></script>
<script type="text/javascript" src="/revolution/js/extensions/revolution.extension.kenburn.min.js"></script>

</body>

resources/views/layouts/menusidebar.blade.php
<div class="col-xl-3 col-lg-4 order-lg-1">
    <button class="sidebar-toggle position-left" data-toggle="modal" data-target="#modalShopFilters"><i class="icon-layout"></i></button>
    <aside class="sidebar sidebar-offcanvas" style="padding-top: 75px">

        <!-- Widget Price Range-->

        <section class="widget widget-categories">
            <h3 class="widget-title">Prijs</h3>
{{--            <form action="javascript:;" class="price-range-slider" method="post" data-start-min="{{ \Request::get('filterPriceMin','0') }}" data-start-max="{{ \Request::get('filterPriceMax','50') }}" data-min="0" data-max="50" data-step="1">--}}
                <div class="ui-range-slider"></div>
                <footer class="ui-range-slider-footer">
                    <div class="column">
                        <button class="btn btn-outline-primary btn-sm" onclick="filterData()" type="submit">Filter</button>
                    </div>
                    <div class="column">
                        <div class="ui-range-values">
                            <div class="ui-range-value-min">&euro;<span></span>
                                <input type="hidden">
                            </div>&nbsp;-&nbsp;
                            <div class="ui-range-value-max">&euro;<span></span>
                                <input type="hidden">
                            </div>
                        </div>
                    </div>
                </footer>
{{--            </form>--}}
        </section>


        <section class="widget widget-categories">
            <h3 class="widget-title">Filter
                @if(\Request::segment(2) == 'filter-list')
                    <button class="btn btn-outline-primary btn-sm" onclick='window.location.href= "{{ route("pages.filter-product-list") }}"' type="button" style="font-size: 10px; height: 22px;padding: 0 9px; border-radius: 12px;line-height: 14px">RESET</button>
                @else
                    <button class="btn btn-outline-primary btn-sm" onclick='window.location.href= "{{ route("pages.filter-product-grid") }}"' type="button"  style="font-size: 10px; height: 22px;padding: 0 9px; border-radius: 12px;line-height: 14px">RESET</button>
                @endif
            </h3>

            @if(!empty(\Request::get('subcat')))
                <div class="column">
                    @foreach(\Request::get('subcat') as $subcategory)
                        <button class="btn btn-outline-primary btn-sm" style="font-size: 10px; height: 22px;padding: 0 9px; border-radius: 12px;line-height: 14px"onclick="return $('input#{{ $subcategory }}').trigger('click')" type="button"> x {{ $subcategory }}</button>
                    @endforeach
                </div>
            @endif
            <ul>

                @foreach($categories->where('visible' , '1') as $category)
                    <li class="has-children expanded" ><a href="javascript:;">{{$category->maincat}}</a>
                        <ul>

                            @foreach(App\Models\LM::where('maincat' , $category->maincat)->groupBy('subcat')->pluck('subcat') as $subcategory)
                                <li>
                                    <?php
                                    $checked = '';
                                    if(!empty(\Request::get('subcat'))){
                                        $checked = in_array($subcategory,\Request::get('subcat'))?"checked":"";
                                    }

                                    ?>
                                    <input type="checkbox" id="{{ $subcategory }}" {{$checked }} onchange="filterData()" value="{{ $subcategory }}" name="subcat[]" />
                                    <label for="{{ $subcategory }}">
                                        <a href="javascript:;"><span>{{$subcategory}}</span></a>
                                    </label>
                                </li>
                            @endforeach
                        </ul>
                    </li>

                @endforeach


            </ul>
        </section>


        <!-- Promo Banner-->

        {{--<section class="promo-box" style="background-image: url(https://www.benel.nl/images/webshop/matin-smartphone-adapter-cr3-m-7123-full-169769-1-38160-114.jpg);">--}}
        {{--<!-- Choose between .overlay-dark (#000) or .overlay-light (#fff) with default opacity of 50%. You can overrride default color and opacity values via 'style' attribute.--><span class="overlay-dark" style="opacity: .45;"></span>--}}
        {{--<div class="promo-box-content text-center padding-top-3x padding-bottom-2x">--}}
        {{--<h4 class="text-light text-thin text-shadow">Nieuw!!</h4>--}}
        {{--<h3 class="text-bold text-light text-shadow">Smartphone fotografie</h3><a class="btn btn-sm btn-primary" href="/category/subcategory-list/Smartphone_Accessoires" >Shop Nu</a>--}}
        {{--</div>--}}
        {{--</section>--}}


        {{--<br><br>--}}


        {{--<!-- Promo2 Banner-->--}}

        {{--<section class="promo-box" style="background-image: url(https://www.benel.nl/images/webshop/falcon-eyes-led-lamp-set-dimbaar-dv-160v-met-statieven-full-2204-1-36074-116.jpg);">--}}
        {{--<!-- Choose between .overlay-dark (#000) or .overlay-light (#fff) with default opacity of 50%. You can overrride default color and opacity values via 'style' attribute.--><span class="overlay-dark" style="opacity: .45;"></span>--}}
        {{--<div class="promo-box-content text-center padding-top-3x padding-bottom-2x">--}}
        {{--<h4 class="text-light text-thin text-shadow">Creeër je perfecte foto met de juiste belichting waar je ook bent!!</h4>--}}
        {{--<h5 class="text-bold text-light text-shadow">Falcon Eyes Soft LED Lamp Set DV-80SL incl. 2 accu's en handvat</h5><a class="btn btn-sm btn-primary" href="/category/subcategory-list/single-product/2228" >Shop Nu</a>--}}
        {{--</div>--}}
        {{--</section>--}}


    </aside>
</div>
<style>

    a {
        color: white
    }
</style>
<script>

    $(document).ready(function(){

        fill_datatable();

        function fill_datatable(filter_brand = '')
        {
            var dataTable = $('#customer_data').DataTable({
                processing: true,
                serverSide: true,
                ajax:{
                    url: "{{ route('subcategory-grid.index') }}",
                    data:{filter_brand:filter_brand}
                },
                columns: [
                    {
                        data:'sub_category_url',
                        name:'sub_category_url'
                    },
                    {
                        data:'artnr',
                        name:'artnr'
                    },
                    {
                        data:'art_description_NL',
                        name:'art_description_NL'
                    },
                    {
                        data:'image_url_1',
                        name:'image_url_1'
                    },
                    {
                        data:'stock',
                        name:'stock'
                    },
                    {
                        data:'price',
                        name:'price'
                    },
                    {
                        data:'purchase_exbtw',
                        name:'purchase_exbtw'
                    }
                ]
            });
        }

        $('#filter').click(function(){
            var filter_brand = $('#filter_brand').val();


            if(filter_gender != '')
            {
                $('#customer_data').DataTable().destroy();
                fill_datatable(filter_brand);
            }
            else
            {
                alert('Select Both filter option');
            }
        });

        $('#reset').click(function(){
            $('#filter_brand').val('');
            $('#brand').DataTable().destroy();
            fill_datatable();
        });

    });
</script>

resources/views/layouts/minicart.blade.php
<a href="/shoppingcart"></a><i class="icon-bag"></i>
<span class="count" style="font-size: 18px">
    {{ Session::has('cart') ? Session::get('cart')->totalQty : '' }}
</span>
<span class="subtotal" style="font-size: 18px">€ {{ round(Session::has('cart') ? Session::get('cart')->totalPrice : '' , 2)}}</span>
<div class="toolbar-dropdown" id="cart-toolbar" style="background-color: #191919">
    @if (!Session::has('cart'))
        <img src="/img/emptycart.png" style="padding-bottom: 20px"><br>
        <span>Winkelwagen is leeg</span>
    @else

        @foreach (Session::get('cart')->items as $product)

            <div class="dropdown-product-item">
                <span class="dropdown-product-remove">
                   <a class="remove-from-cart" href="{{ route('product.remove', ['id'=> $product['item']['id']])}}" data-toggle="tooltip"
                      title="Remove item"><i class="icon-cross"></i>
                   </a>
                </span>

                <a class="dropdown-product-thumb" href="category/subcategory-grid/single-product/{{$product['item']['artnr']}}">
                    <img src="{{$product['item'] ['image_1']}}" alt="Product">
                </a>
                <div class="dropdown-product-info">
                    <a class="dropdown-product-title"
                       href="{{$product['item']['artnr']}}">{{$product['item'] ['name']}}</a>
                    <span class="dropdown-product-details">{{$product['qty']}}
                        x €{{(round($product['item']['price'] , 2 ))}}</span>
                </div>
            </div>
        @endforeach
     @endif
     @if(Session::has('cart'))
        <div class="toolbar-dropdown-group" >
          <div class="column"><span class="text-lg">Totaal:</span></div>
          <div class="column text-right"><span class="text-lg text-medium">€{{ number_format((Session::has('cart')) ? Session::get('cart')->totalPrice : '' , 2)}}&nbsp;</span></div>
        </div>
    @endif
    <div class="toolbar-dropdown-group">
        <div class="column"><a class="btn btn-sm btn-block btn-secondary" href="/shoppingcart" style="font-size: 11px">Winkelwagen</a></div>
        @if (!Session::has('cart'))
        @else
            <div class="column"><a class="btn btn-sm btn-block btn-success" href="/checkout-address" style="font-size: 11px">Bestellen</a></div>
        @endif
    </div>
</div>

resources/views/layouts/pagination.blade.php
<head>


    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  </head>

@yield('content')